### ISSUE TITLE
npm install failed in nodejs v0.10.3

### ISSUE THREAD

**Issue by yunjiali** [Colingo/srt-parser#2]
Hi, thanks for your nice work. I have got following error message when installing the module with "npm install srt"

<pre>
npm ERR! Error: invalid version: 0.2
npm ERR!     at validVersion (/Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:571:40)
npm ERR!     at final (/Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:323:23)
npm ERR!     at /Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:139:33
npm ERR!     at cb (/Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:316:40
npm ERR!     at fs.js:266:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 11.4.2
npm ERR! command "/Users/user/.nvm/v0.10.3/bin/node" "/Users/user/.nvm/v0.10.3/bin/npm" "install" "srt"
npm ERR! cwd /Users/user/projects/someproject
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/user/projects/someproject/npm-debug.log
npm ERR! not ok code 0
</pre>

I am using nvm to control the node version on my machine. When I use v0.6.16, everything is fine. Any idea on the installation problem? Many thanks.

**Comment by robertjd** [comment]
Hey, can you show us what is in `/Users/user/projects/someproject/npm-debug.log`

thanks!

**Comment by yunjiali** [comment]
It's very strange that I didn't find npm-debug.log in the project root folder and it's not in the "logs" folder, neither. In addition, I have tried install it under v0.10.3 for other projects on my machine, and they all seem OK this time. So it might be the problem of nvm.

**Comment by yunjiali** [comment]
OK. I uninstalled the module and re-install it again, then I got this problem again. The npm-debug.log is:

<pre>
 info it worked if it ends with ok
1 verbose cli [ '/Users/user/.nvm/v0.10.3/bin/node',
1 verbose cli   '/Users/user/.nvm/v0.10.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   'srt' ]
2 info using npm@1.2.17
3 info using node@v0.10.3
4 verbose read json /Users/user/projects/synote-multimedia-service/package.json
5 error Error: invalid version: 0.2
5 error     at validVersion (/Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:571:40)
5 error     at final (/Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:323:23)
5 error     at /Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:139:33
5 error     at cb (/Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
5 error     at /Users/user/.nvm/v0.10.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:251:40
5 error     at fs.js:266:14
5 error     at Object.oncomplete (fs.js:107:15)
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Darwin 11.4.2
8 error command "/Users/user/.nvm/v0.10.3/bin/node" "/Users/user/.nvm/v0.10.3/bin/npm" "install" "srt"
9 error cwd /Users/user/projects/synote-multimedia-service
10 error node -v v0.10.3
11 error npm -v 1.2.17
12 verbose exit [ 1, true ]
</pre>

**Comment by Raynos** [comment]
srt installs fine with node `v0.10.5` and npm `v1.2.20`

``` sh
raynos at raynos-Latitude-E5530-non-vPro  ~
$ npm i srt
srt@0.0.3 node_modules/srt
└── ap@0.1.0
raynos at raynos-Latitude-E5530-non-vPro  ~
$ node --version
v0.10.5
raynos at raynos-Latitude-E5530-non-vPro  ~
$ npm --version
1.2.20
```

Closing for now. If you can reproduce the issue with those versions then let me know and I'll look into it.
